version: '3.1'

services:
  app:
    restart: always
    build: ./nginx
    working_dir: /app
    volumes:
      - ../../kafka-twitter:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    command: mvn clean install spring-boot:run -Dspring-boot.run.arguments="${SPRINGARGS}"

  nginx:
    container_name: nginx-contaner
    image: nginx:1.13
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
