version: '3.1'

networks:
  kafka-net:
    driver: bridge

services:

  app:
    restart: always
    build: ./nginx
    working_dir: /app
    volumes:
      - ../../kafka-twitter:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    command: mvn clean install spring-boot:run -Dspring-boot.run.arguments="ARGUMENTS_HERE"
    depends_on:
      - zookeeper
      - kafka-s1s
  nginx:
    container_name: nginx-contaner
    image: nginx:1.13
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  zookeeper:
    image: 'zookeeper:3.5.7'
    restart: always
    hostname: zookeeper
    ports:
        - 2181:2181
    networks:
      - kafka-net

  kafka-s1:
    image: 'bitnami/kafka:2.4.1'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-net

  elasticsearch:
    image: 'bitnami/elasticsearch:7'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './elasticsearch_data:/bitnami/elasticsearch/data'
